name       : yakuake
version    : 19.12.1
release    : 11
source     :
    - https://cdn.download.kde.org/stable/release-service/19.12.1/src/yakuake-19.12.1.tar.xz : abff4f358f41f544b2e12c340a74d92482241b1b95906b14add7810384602e42
homepage   : https://kde.org/applications/system/org.kde.yakuake
license    : GPL-2.0
component  : desktop.kde
summary    : A quake style dropdown terminal.
description: |
    A quake-inspired dropdown terminal window.  Qt-based, robust, and highly configurable.
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5Widgets)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(gl)
    - extra-cmake-modules
    - karchive-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kglobalaccel-devel
    - kiconthemes-devel
    - knewstuff-devel
    - knotifications-devel
    - knotifyconfig-devel
    - kparts-devel
    - kwayland-devel
    - kwindowsystem-devel
rundeps    :
    - konsole
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
