name       : yakuake
version    : 19.08.1
release    : 6
source     :
    - https://cdn.download.kde.org/stable/applications/19.08.1/src/yakuake-19.08.1.tar.xz : 184fec9d07505faf820821e197582f7733694848cc17e71ee4f525772e78fc10
license    : GPL-2.0
component  : desktop.kde
summary    : A quake style dropdown terminal.
description: |
    A quake-inspired dropdown terminal window.  Qt-based, robust, and highly configurable.
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5Widgets)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(gl)
    - extra-cmake-modules
    - karchive-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kglobalaccel-devel
    - kiconthemes-devel
    - knewstuff-devel
    - knotifications-devel
    - knotifyconfig-devel
    - kparts-devel
    - kwayland-devel
    - kwindowsystem-devel
rundeps    :
    - konsole
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
