name       : yakuake
version    : 19.08.2
release    : 7
source     :
    - https://cdn.download.kde.org/stable/applications/19.08.2/src/yakuake-19.08.2.tar.xz : 3ebf477069c85a8705302b6b51902a74af7bb92349fab41000f71484a4de5aee
license    : GPL-2.0
component  : desktop.kde
summary    : A quake style dropdown terminal.
description: |
    A quake-inspired dropdown terminal window.  Qt-based, robust, and highly configurable.
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5Widgets)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(gl)
    - extra-cmake-modules
    - karchive-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kglobalaccel-devel
    - kiconthemes-devel
    - knewstuff-devel
    - knotifications-devel
    - knotifyconfig-devel
    - kparts-devel
    - kwayland-devel
    - kwindowsystem-devel
rundeps    :
    - konsole
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
