name       : yakuake
version    : 22.04.1
release    : 41
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.1/src/yakuake-22.04.1.tar.xz : 53389837706aa62d56d3965bb846b435fc15a3083e3756c75a25aa86ee65c1b0
homepage   : https://kde.org/applications/system/org.kde.yakuake
license    : GPL-2.0
component  : desktop.kde
summary    : A quake style dropdown terminal.
description: |
    A quake-inspired dropdown terminal window.  Qt-based, robust, and highly configurable.
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5Widgets)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
    - karchive-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kglobalaccel-devel
    - kiconthemes-devel
    - knewstuff-devel
    - knotifyconfig-devel
    - kparts-devel
    - kwayland-devel
rundeps    :
    - konsole
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
