name       : yakuake
version    : 22.04.2
release    : 42
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.2/src/yakuake-22.04.2.tar.xz : 046c7f91d10363b8bd09c6eb254ad06587dcc26259a3e1952f5ba5c7f4b94b28
homepage   : https://kde.org/applications/system/org.kde.yakuake
license    : GPL-2.0
component  : desktop.kde
summary    : A quake style dropdown terminal.
description: |
    A quake-inspired dropdown terminal window.  Qt-based, robust, and highly configurable.
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5Widgets)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
    - karchive-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kglobalaccel-devel
    - kiconthemes-devel
    - knewstuff-devel
    - knotifyconfig-devel
    - kparts-devel
    - kwayland-devel
rundeps    :
    - konsole
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
