name       : yakuake
version    : 20.12.3
release    : 28
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.3/src/yakuake-20.12.3.tar.xz : 7ddd1a47fdd3af67be16ae40182bea97f7c004448391ac52737d3e5f2e0b25f8
homepage   : https://kde.org/applications/system/org.kde.yakuake
license    : GPL-2.0
component  : desktop.kde
summary    : A quake style dropdown terminal.
description: |
    A quake-inspired dropdown terminal window.  Qt-based, robust, and highly configurable.
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5Widgets)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
    - karchive-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kglobalaccel-devel
    - kiconthemes-devel
    - knewstuff-devel
    - knotifyconfig-devel
    - kparts-devel
    - kwayland-devel
rundeps    :
    - konsole
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
