name       : yakuake
version    : 3.0.4
release    : 2
source     :
    - https://download.kde.org/stable/yakuake/3.0.4/src/yakuake-3.0.4.tar.xz : 10e2b57c508e2ec5bfd09eac38c4c16a1ac4b93b394b3ce3120b7d8859b861e0
license    : GPL-2.0
component  : desktop.kde.core
summary    : A quake style dropdown terminal.
description: |
    A quake-inspired dropdown terminal window.  Qt-based, robust, and highly configurable.
builddeps  :
    - pkgconfig(Qt5Widgets)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(gl)
    - extra-cmake-modules
    - kparts-devel
    - kwindowsystem-devel
    - knewstuff-devel
    - karchive-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kglobalaccel-devel
    - kiconthemes-devel
    - knotifications-devel
    - knotifyconfig-devel
rundeps    :
    - konsole
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
