name       : yakuake
version    : 21.08.2
release    : 35
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.2/src/yakuake-21.08.2.tar.xz : 0f12ff2124d05e4da17a2337f31c982f95bd799b7505e850bda4de2941800db5
homepage   : https://kde.org/applications/system/org.kde.yakuake
license    : GPL-2.0
component  : desktop.kde
summary    : A quake style dropdown terminal.
description: |
    A quake-inspired dropdown terminal window.  Qt-based, robust, and highly configurable.
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5Widgets)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
    - karchive-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kglobalaccel-devel
    - kiconthemes-devel
    - knewstuff-devel
    - knotifyconfig-devel
    - kparts-devel
    - kwayland-devel
rundeps    :
    - konsole
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
